[
  {
    category_name: "인기 메뉴",
    id: 1,
    display_order: 1,
    main_menus: [
      {
        id: 1,
        name: "콤보라이스 (Combo Rice)",
        price: 11900,
        description:
          "바스마티라이스, 양상추, 토마토, 그릴에서 볶은 닭고기와 양고기, 화이트소스, 레드소스, 할라피뇨, 플랫브레드",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/1.PNG",
        display_order: 1,
        menu_status: true,
      },
      {
        id: 2,
        name: "치킨 오버 라이스 (Chicken Over Rice)",
        price: 11700,
        description:
          "바스마티라이스, 양상추, 토마토, 그릴에서 볶은 닭고기, 화이트소스, 레드소스, 할라피뇨, 플랫브레드",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/2.PNG",
        display_order: 2,
        menu_status: true,
      },
      {
        id: 3,
        name: "램 오버 라이스 (Lamb Over Rice",
        price: 11900,
        description:
          "바스마티라이스, 양상추, 토마토, 그릴에서 볶은 양고기, 화이트소스, 레드소스, 할라피뇨, 플랫브레드",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/3.PNG",
        display_order: 3,
        menu_status: true,
      },
      {
        id: 4,
        name: "램 라이스 랩 (Lamb Rice Wrap)",
        price: 9900,
        description: "",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/4.PNG",
        display_order: 4,
        menu_status: true,
      },
      {
        id: 5,
        name: "치킨 라이스 랩 (Chicken Rice Wrap)",
        price: 9700,
        description: "",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/5.PNG",
        display_order: 5,
        menu_status: true,
      },
    ],
  },
  {
    category_name: "메뉴",
    id: 2,
    display_order: 2,
    main_menus: [
      {
        id: 6,
        name: "치킨 오버 라이스 (Chicken Over Rice)",
        price: 11700,
        description:
          "바스마티라이스, 양상추, 토마토, 그릴에서 볶은 닭고기, 화이트소스, 레드소스, 할라피뇨, 플랫브레드",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/6.PNG",
        display_order: 1,
        menu_status: true,
      },
      {
        id: 7,
        name: "램 오버 라이스 (Lamb Over Rice",
        price: 11900,
        description:
          "바스마티라이스, 양상추, 토마토, 그릴에서 볶은 양고기, 화이트소스, 레드소스, 할라피뇨, 플랫브레드",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/7.PNG",
        display_order: 2,
        menu_status: true,
      },
      {
        id: 8,
        name: "콤보라이스 (Combo Rice)",
        price: 11900,
        description:
          "바스마티라이스, 양상추, 토마토, 그릴에서 볶은 닭고기와 양고기, 화이트소스, 레드소스, 할라피뇨, 플랫브레드",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/8.PNG",
        display_order: 3,
        menu_status: true,
      },
      {
        id: 9,
        name: "치킨 라이스 랩 (Chicken Rice Wrap)",
        price: 9700,
        description: "",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/9.PNG",
        display_order: 4,
        menu_status: true,
      },
      {
        id: 10,
        name: "램 라이스 랩 (Lamb Rice Wrap)",
        price: 9900,
        description: "",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/10.PNG",
        display_order: 5,
        menu_status: true,
      },
      {
        id: 11,
        name: "치킨 랩 샌드위치 (Chicken Wrap Sandwich)",
        price: 6200,
        description: "",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/11.PNG",
        display_order: 6,
        menu_status: true,
      },
      {
        id: 12,
        name: "램 랩 샌드위치 (Lamb Wrap Sandwich)",
        price: 6500,
        description: "",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/12.PNG",
        display_order: 7,
        menu_status: true,
      },
    ],
  },
  {
    category_name: "세트",
    id: 3,
    display_order: 3,
    main_menus: [
      {
        id: 13,
        name: "치킨 오버 라이스 세트 (Chicken Over Rice Set)",
        price: 16700,
        description: "치킨 오버 라이스 + 감자튀김 or 나쵸, 음료 선택",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/13.PNG",
        display_order: 1,
        menu_status: true,
      },
      {
        id: 14,
        name: "램 오버 라이스 세트 (Lamb Over Rice Set",
        price: 16900,
        description: "램 오버 라이스 + 감자튀김 or 나쵸, 음료 선택",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/14.PNG",
        display_order: 2,
        menu_status: true,
      },
      {
        id: 15,
        name: "콤보라이스 세트 (Combo Rice Set)",
        price: 16900,
        description: "콤보라이스 + 감자튀김 or 나쵸, 음료 선택",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/15.PNG",
        display_order: 3,
        menu_status: true,
      },
      {
        id: 16,
        name: "치킨 라이스 랩 세트 (Chicken Rice Wrap Set)",
        price: 13900,
        description: "치킨 라이스 랩 + 감자튀김 or 나쵸, 음료 선택",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/16.PNG",
        display_order: 4,
        menu_status: true,
      },
      {
        id: 17,
        name: "램 라이스 랩 세트 (Lamb Rice Wrap Set)",
        price: 14300,
        description: "랩 라이스 랩 + 감자튀김 or 나쵸, 음료 선택",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/17.PNG",
        display_order: 5,
        menu_status: true,
      },
      {
        id: 18,
        name: "치킨 랩 샌드위치 세트 (Chicken Wrap Sandwich Set)",
        price: 11700,
        description: "치킨 랩 샌드위치 + 감자튀김 or 나쵸, 음료 선택",
        image_url: "https://spqr-menu.s3.ap-northeast-2.amazonaws.com/1/18.PNG",
        display_order: 6,
        menu_status: true,
      },
      {
        id: 19,
        name: "램 랩 샌드위치 세트 (Lamb Wrap Sandwich Set)",
        price: 12000,
        description: "램 랩 샌드위치 + 감자튀김 or 나쵸, 음료 선택",
        image_url: "",
        display_order: 7,
        menu_status: true,
      },
    ],
  },
];
